message("\n\n##########################################################################\n",
        "# Start LD_E02a2 Pseudobulk DESeq2 analysis: ", Sys.time(),
        "\n##########################################################################\n",
        "\n   LRT test by cluster with correction for covariates",
        "\n##########################################################################\n\n")

# This script performs pseudobulk DESeq2 differential gene expression analysis on astrocyte subclusters.
# It takes the pseudobulk count data generated by E01, runs multiple DESeq2 (R package for differential expression analysis) comparisons.
# compares: 1) each cluster vs reference cluster (common variant only)
#           2) AD vs Control within each cluster (common variant only, correcting for covariates)
#           3) TREM2 variant effects within each cluster (AD cases only, correcting for covariates) R62H vs CV, R47H vs CV, and R47H vs R62H

# Open packages necessary for analysis.
library(qs)
library(tidyverse)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(Seurat)
library(DESeq2)
library(colorRamps)
library(viridis)
library(pheatmap)
library(ggrepel)
library(WGCNA)


### define directories and script index

main_dir = "/rds/general/user/lvd25/home/AST_scRNAseq_TREM2/"
setwd(main_dir)

#specify script/output index as prefix for file names
script_ind = "LD_E02a2_"

#specify output directory
out_dir = paste0(main_dir,"LD_E_DESeq_pseudobulk/")



### load dataset; define variables required for DESeq2 models 
# keep clusters with >= 2 samples per level and at least 2 levels for each categorical variable

bulk_data = qread(file = paste0(out_dir, "LD_E01_bulk_data.qs")) 

t1 = bulk_data$meta
names(t1)

#define model variables
model_vars = c("cohort", "APOEgroup", "CD33Group", "BrainRegion", 
               "NeuropathologicalDiagnosis", "TREM2Variant")

t1$NeuropathologicalDiagnosis = factor(t1$NeuropathologicalDiagnosis, levels = c("Control", "AD"))

t1$APOEgroup = factor(t1$APOEgroup, levels = c("APOE4-neg", "APOE4-pos"))
t1$CD33Group = factor(t1$CD33Group, levels = c("CV", "CD33var"))
t1$BrainRegion = factor(t1$BrainRegion, levels = c("SSC", "MTG"))
t1$cohort = factor(t1$cohort, levels = c("BiogenInitial", "BiogenExtra"))

# define covariates to correct vst matrix for
covars_corr = c("cohort", "APOEgroup", "CD33Group", "BrainRegion")

# define reference cluster for between cluster "response" comparisons
ref_cluster = "AST_SLC1A2_s0" # changed from HOM_s0 for MIC

#remove samples with missing covariate values
for (var1 in model_vars){
  t1 = t1[!is.na(t1[[var1]]),]
}

#filter for clusters containing at least 2 samples for 2 different levels for all analysed variables -->  DESeq2 can't estimate effects without variation

for (var1 in model_vars){
  t1$model_var = t1[[var1]]
  t2 = t1 %>% group_by(cluster_name, model_var) %>% summarise(N_samples = n())
  t3 = t2[t2$N_samples>=2,] %>% group_by(cluster_name) %>% summarise(N_levels = n())
  t1 = t1[t1$cluster_name %in% t3$cluster_name[t3$N_levels>1],]
}

bulk_data$meta = t1


### update bulkdata object, extract group tab
m1 = bulk_data$counts
m2 = m1[,bulk_data$meta$cluster_sample]
bulk_data$counts = m2

gr_tab = bulk_data$gr_tab[bulk_data$gr_tab$sample %in% bulk_data$meta$sample,]
bulk_data$gr_tab = gr_tab



###get marker gene panels
# reads a list of genes known to encode transcriton factors, to be used for plotting later on.
GOI = list()
t1 = read_csv(paste0(main_dir,"data_TREM2_michael/A_input/Transcription Factors hg19 - Fantom5_21-12-21.csv"))
GOI$TF = t1$Symbol



###########################################################
# functions
###########################################################

#custom colour palette for variable values defined in vector v
pal = function(v){
  v2 = length(unique(v))
  if (v2 == 2){
    p2 = c("grey20", "dodgerblue")
  } else if (v2 ==3){
    p2 = c("dodgerblue", "grey20", "orange")
  } else if (v2 ==4){
    p2 = c("dodgerblue", "green4","grey20", "orange")
  } else if (v2<6){
    p2 = matlab.like(6)[1:v2]
  } else {
    p2 = matlab.like(v2)
  }
  return(p2)
}


###function: plot bulk gene expression heatmap with annotations

bulkdata_heatmap = function(pl_mat, pl_meta, x_col, 
                            p_mat = FALSE,
                            pl_genes = NULL, 
                            meta_annot_cols = NULL,
                            cluster_rows = TRUE, cluster_cols = FALSE,
                            show_rownames = TRUE, show_colnames = TRUE,
                            color = colorRampPalette(c("magenta", "black", "yellow"))(250),
                            lims = NULL,  cellwidth = 15, cellheight = 10, 
                            fontsize = 10, number_color = "grey70",
                            title = "Z-score vst-norm gene expression"){
  
  if (is.null(pl_genes)){pl_genes = rownames(pl_mat)}
  
  pl_mat = pl_mat[match(pl_genes, rownames(pl_mat), nomatch = 0),]
  pl_meta = pl_meta[match(pl_meta[[x_col]], colnames(pl_mat), nomatch = 0),]
  
  #define annotation bars
  
  if (!is.null(meta_annot_cols)){
    
    annot_col = data.frame(row.names = pl_meta[[x_col]]) #if not defined cbind converts factor values to factor levels
    
    for (col1 in meta_annot_cols){
      v1 = pl_meta[match(colnames(pl_mat), pl_meta[[x_col]]),][[col1]]
      if (is.numeric(v1)){v1 = factor(v1, levels = unique(pl_meta[[col1]][order(pl_meta[[col1]])]))} else {
        v1 = factor(v1, levels = unique(pl_meta[[col1]]))
      }
      annot_col = as.data.frame(cbind(annot_col, v1))
    }
    colnames(annot_col) = meta_annot_cols
    rownames(annot_col) = colnames(pl_mat)
    
    annot_colors = lapply(meta_annot_cols, function(x){
      v1 = pal(unique(annot_col[[x]]) )
      names(v1) = levels(annot_col[[x]])
      return(v1)
    })
    names(annot_colors) = meta_annot_cols
    
  }else{
    annot_col = NULL
    annot_colors = NULL
  }
  
  # define plot limits
  
  if (is.null(lims)){lims = c(-0.7*max(abs(na.omit(pl_mat))), 0.7*max(abs(na.omit(pl_mat))))}
  
  #create plot
  
  p1 = pheatmap::pheatmap(pl_mat, 
                          display_numbers = p_mat,
                          cluster_rows = cluster_rows, cluster_cols = cluster_cols,
                          show_rownames = show_rownames, show_colnames = show_colnames,
                          color = color,
                          breaks = seq(lims[1], lims[2], length.out = length(color)+1),
                          annotation_col = annot_col, annotation_colors = annot_colors,
                          border_color = NA, cellwidth = cellwidth, cellheight = cellheight, 
                          fontsize = fontsize, number_color = number_color, fontsize_number = fontsize, 
                          main = title
  )
  
  return(p1)
  
}




###########################################################
# Preparing dataset for DESeq2 analysis
###########################################################

message("\n\n          *** Preparing dataset for DESeq2 analysis... ", Sys.time(),"\n\n")

comp_meta = bulk_data$meta

comp_clusters = unique(comp_meta$cluster_name)

#remove genes from countmatrix with <0.1 counts/cell in all pseudobulks  --> fikters out very lowly expressed genes

m1 = bulk_data$counts

keep_genes = rownames(m1)[apply(m1, 1, max)>0.1]

comp_counts = m1[keep_genes,]

bulk_data$counts = comp_counts



#######################################
# calculate uncorrected and corrected vst matrix and corresponding gene z-scores
#######################################
# vst = variance stabilising transformation to make sure that data is roughly homoscedastic and variance is similar across low and high expression genes
### extract vst-normalised matrix for combined dataset

dds = DESeqDataSetFromMatrix(comp_counts, colData = comp_meta, 
                             design = ~group)

bulk_data$deseq_dataset_groups_clusters_combined = dds

# extract vst norm expression matrix (based on all clusters combined), correct for covariates, calculate gene z-scores 

dds = bulk_data$deseq_dataset_groups_clusters_combined

vst_mat = assay(vst(dds))

bulk_data$vst_mat_uncorr = vst_mat

#batch-correct vst matrix
vst_mat_corr = vst_mat

for (cov1 in covars_corr){
  if (length(unique(comp_meta[[cov1]]))>1){
    vst_mat_corr = limma::removeBatchEffect(vst_mat_corr, batch = comp_meta[[cov1]])
  } else {vst_mat_corr = vst_mat_corr}
}

bulk_data$vst_mat = vst_mat_corr

#calculate Z-score per gene by pseudobulk (cluster_sample) for all clusters combined (from uncorrected and corrected vst matrix)
cluster_sample_mat = t(apply(vst_mat, 1, scale))
colnames(cluster_sample_mat) = colnames(vst_mat)
bulk_data$gene_Z_scores_uncorr[["clusters_combined"]] = cluster_sample_mat

cluster_sample_mat = t(apply(vst_mat_corr, 1, scale))
colnames(cluster_sample_mat) = colnames(vst_mat_corr)
bulk_data$gene_Z_scores[["clusters_combined"]] = cluster_sample_mat



#######################################
# plot PCA plot samples (by cluster, based on uncorrected vst matrix)
#######################################
# For each cluster individually and for all clusters combined: Selects top 3000 most variable genes (these drive the most biological variation),
# performs PCA on the vst-normalised expression of these genes, and plots the first 2 principal components with samples colored by group (TREM2 variant and diagnosis groups)
# and labelled by sample ID. This is done separately for the uncorrected vst matrix and the covariate-corrected vst matrix, to assess how well samples cluster by group and whether there are any outliers or batch effects.
meta = bulk_data$meta

samples = unique(bulk_data$gr_tab$sample)
gr = unique(bulk_data$gr_tab$group)

vst_mat = bulk_data$vst_mat_uncorr

#identify top 3000 variable genes
v1 = rowVars(vst_mat)
var_genes = names(v1[order(-v1)][1:3000])


### plot PCA by cluster

pl = list()

cl = "AST_SLC1A2_s4" # changed from HOM...for MIC

for (cl in comp_clusters){
  
  meta_cl = meta[meta$cluster_name == cl,]
  
  m1 = vst_mat[var_genes,meta_cl$cluster_sample]
  z_mat_cl = scale(m1)
  
  pc_analysis = prcomp(z_mat_cl)
  
  meta_pca = cbind(meta_cl, pc_analysis$rotation)
  meta_pca$sample_label = paste0(meta_pca$sample)
  
  pl[[paste0(cl, "_PC1_PC2")]] = ggplot(meta_pca)+geom_point(aes(x = PC1, y = PC2, color = group))+
    geom_text_repel(aes(x = PC1, y = PC2, label = sample_label, color = group))+
    scale_color_manual(limits = gr, values = pal(gr))+
    theme_minimal()+labs(title = paste0(cl, "- PC1 vs PC2 "))
  
}


### plot PCA all clusters

meta_cl = meta

m1 = vst_mat[var_genes,]
z_mat_cl = scale(m1)

pc_analysis = prcomp(z_mat_cl)

meta_pca = cbind(meta_cl, pc_analysis$rotation)
meta_pca$sample_label = paste0(meta_pca$cluster_sample)

pl[["all_clusters"]] = ggplot(meta_pca)+geom_point(aes(x = PC1, y = PC2, color = group))+
  geom_text_repel(aes(x = PC1, y = PC2, label = sample_label, color = group))+
  scale_color_manual(limits = gr, values = pal(gr))+
  theme_minimal()+labs(title = paste0(" all_clusters - PCA "))


pdf(file = paste0(out_dir,script_ind, "PCA_plot_samples_by_cluster_uncorr.pdf"), 
    width = 7, height = 6)
{
  lapply(pl, function(x){x})
}
dev.off()



#######################################
# plot PCA plot samples (by cluster, based on corrected vst matrix)
#######################################

meta = bulk_data$meta

samples = unique(bulk_data$gr_tab$sample)
gr = unique(bulk_data$gr_tab$group)

vst_mat = bulk_data$vst_mat

#identify top 3000 variable genes
v1 = rowVars(vst_mat)
var_genes = names(v1[order(-v1)][1:3000])


### plot PCA by cluster

pl = list()

for (cl in comp_clusters){
  
  meta_cl = meta[meta$cluster_name == cl,]
  
  m1 = vst_mat[var_genes,meta_cl$cluster_sample]
  z_mat_cl = scale(m1)
  
  pc_analysis = prcomp(z_mat_cl)
  
  meta_pca = cbind(meta_cl, pc_analysis$rotation)
  meta_pca$sample_label = paste0(meta_pca$sample)
  
  pl[[paste0(cl, "_PC1_PC2")]] = ggplot(meta_pca)+geom_point(aes(x = PC1, y = PC2, color = group))+
    geom_text_repel(aes(x = PC1, y = PC2, label = sample_label, color = group))+
    scale_color_manual(limits = gr, values = pal(gr))+
    theme_minimal()+labs(title = paste0(cl, "- PC1 vs PC2 "))
  
}


### plot PCA all clusters

meta_cl = meta

m1 = vst_mat[var_genes,]
z_mat_cl = scale(m1)

pc_analysis = prcomp(z_mat_cl)

meta_pca = cbind(meta_cl, pc_analysis$rotation)
meta_pca$sample_label = paste0(meta_pca$cluster_sample)

pl[["all_clusters"]] = ggplot(meta_pca)+geom_point(aes(x = PC1, y = PC2, color = group))+
  geom_text_repel(aes(x = PC1, y = PC2, label = sample_label, color = group))+
  scale_color_manual(limits = gr, values = pal(gr))+
  theme_minimal()+labs(title = paste0(" all_clusters - PCA "))


pdf(file = paste0(out_dir,script_ind, "PCA_plot_samples_by_cluster_corr.pdf"), 
    width = 7, height = 6)
{
  lapply(pl, function(x){x})
}
dev.off()



#######################################
# Run DESeq2 analysis cluster X vs ref_cluster (common variant only)
#######################################
# compares pseudobulk expression of that cluster against AST_SLC1A2_s0, using only CV samples.
# identifies genes that are differentially expressed between astrocyte subtypes in the absence of TREM2 mutations (regardles of AD vs ctrl)

message("\n\n          *** Running DESeq2 analysis  - ", Sys.time(),"\n\n")

bulk_data$deseq_dataset = list()
bulk_data$deseq_info = list()

### analysis cluster X vs ref_cluster (common variant only)

for (cl in comp_clusters[comp_clusters != ref_cluster]){
  
  message("\n          *** Running DESeq2 analysis ", cl, " vs ref_cluster - ", Sys.time(),"\n")
  
  meta_cl = comp_meta[(comp_meta$cluster_name %in% c(cl, ref_cluster) ) & comp_meta$TREM2Variant == "CV",]
  meta_cl$cluster_name = factor(meta_cl$cluster_name, levels = c(ref_cluster, cl))
  
  counts_cl = comp_counts[, meta_cl$cluster_sample]
  
  form_full = "~cluster_name"
  form_red = "~1"
  
  bulk_data$deseq_info[[paste0(cl, "_CV_vs_", ref_cluster)]] = list(form_full = form_full,
                                                                    form_red = form_red)
  
  #run deseq2
  names(meta_cl)
  dds = DESeqDataSetFromMatrix(counts_cl, colData = meta_cl, 
                               design = as.formula(form_full))
  dds = DESeq(dds, test = "LRT", reduced = as.formula(form_red)) 
  
  bulk_data$deseq_dataset[[paste0(cl, "_CV_vs_", ref_cluster)]] = dds
  
}



#######################################
# Run Deseq analysis within clusters CV AD vs Control
#######################################
# for each cluster it tests AD vs ctrl in CV individuals, correcting for covariates (APOE, CD33, BrainRegion, Cohort).
# Q: Which genes change in AD vs Control within each astrocyte cluster, independent of APOE, CD33, and brain region
cl = "AST_SLC1A2_s3" # changed from HOM_s9 for MIC

for (cl in comp_clusters){
  
  message("\n          *** Running DESeq2 analysis  CV AD vs Control by cluster - ", cl, " - ", Sys.time(),"\n")
  
  msg = NULL
  
  meta_cl = comp_meta[comp_meta$cluster_name == cl & comp_meta$TREM2Variant == "CV",]
  counts_cl = comp_counts[, meta_cl$cluster_sample]
  
  form_full = "~APOEgroup + CD33Group + BrainRegion + NeuropathologicalDiagnosis"
  form_red = "~APOEgroup + CD33Group + BrainRegion"
  
  #remove spaces from formula to avoid problems with automatic removal of variables
  form_full = str_remove_all(form_full, " ")
  form_red = str_remove_all(form_red, " ")
  
  #extract variables in model
  model_vars_full = unlist(str_split(str_remove_all(form_full, "~"), "\\+"))
  model_vars_red = unlist(str_split(str_remove_all(form_red, "~"), "\\+"))
  
  
  #remove spaces from formula to avoid problems with automatic removal of variables
  form_full = str_remove_all(form_full, " ")
  form_red = str_remove_all(form_red, " ")
  
  #extract variables in model
  model_vars_full = unlist(str_split(str_remove_all(form_full, "~"), "\\+"))
  model_vars_red = unlist(str_split(str_remove_all(form_red, "~"), "\\+"))
  
  
  ###check whether variables allow calculating model, remove colinear covariates
  
  #check whether model variables have multiple levels, if not, drop from model
  for (var1 in model_vars_red){
    
    meta_cl$model_var = meta_cl[[var1]]
    
    t2 = meta_cl %>% group_by(model_var) %>% summarise(N_samples = n())
    
    if (nrow(t2)==1){
      form_full = str_remove_all(form_full, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1))
      model_vars_red =  model_vars_red[model_vars_red != var1]
      
      msg = c(msg, paste0("            ! WARNING: Dropping '", var1, "' - All samples have same value \n"))
      message(msg)
    }
  }
  
  #check whether any reduced model variables are colinear, if so remove first variable
  v1 = model_vars_red
  
  for (var1 in v1){
    for (var2 in v1[v1 != var1]){
      
      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3 & str_detect(form_full, var2)){
        form_full = str_remove_all(form_full, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1))
        model_vars_red = model_vars_red[model_vars_red != var1]
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,"' => '", var1, "' dropped")
        message(v2)
        msg = c(msg, v2)
      }
      
      v1 = v1[v1 != var1]
      
    }
  }
  
  #check if covariates are colinear with main predictors of full vs reduced model => if so, omit cluster
  
  omit_cl = FALSE
  
  for (var1 in model_vars_full[!(model_vars_full %in% model_vars_red)]){
    for (var2 in model_vars_red){
      
      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3){
        omit_cl = TRUE
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,
                    "' => effect '", var1, "' cannot be determined => cluster ", cl, " omitted")
        message(v2)
        msg = c(msg, v2)
      }
    }
  }
  
  #if less samples than coefficients (variables+1) omit cluster (model can't be calculated)
  if (nrow(meta_cl) <= length(model_vars_full)+1){
    omit_cl = TRUE
    v1 = paste0("         WARNING: Not enough samples to calculate model => cluster ", cl," ommitted")
    message(v1)
    msg = c(msg, v1)
  }
  
  #if more samples than coefficients (variables+1) run DESeq2 (else model can't be calculated)
  if (omit_cl == FALSE){
    form_full = str_remove(form_full, "\\+$") #remove "+" in end if final variable has been dropped
    form_red = str_remove(form_red, "\\+$")
    dds = DESeqDataSetFromMatrix(counts_cl, colData = meta_cl, 
                                 design = as.formula(form_full))
    dds = DESeq(dds, test = "LRT", reduced = as.formula(form_red)) 
    
    bulk_data$deseq_dataset[[paste0(cl, "_TREM2_CV_AD_vs_Control")]] = dds
  } 
  
  message(msg)
  
  bulk_data$deseq_info[[paste0(cl, "_TREM2_CV_AD_vs_Control")]] = list(form_full = form_full,
                                                                    form_red = form_red,
                                                                    msg = msg)
}



#######################################
# Run Deseq analysis within clusters TREM2 R62H vs CV (only AD cases) 
#######################################
# for each cluster it tests TREM2 R62H vs CV in AD individuals, correcting for covariates (APOE, CD33, BrainRegion, Cohort).
cl = "AST_GFAP_s2" # changed from IRM_s14 for MIC

for (cl in comp_clusters){
  
  message("\n          *** Running DESeq2 analysis AD R62H vs CV by cluster - ", cl, " - ", Sys.time(),"\n")
  
  msg = NULL
  
  meta_cl = comp_meta[comp_meta$cluster_name == cl & 
                        comp_meta$NeuropathologicalDiagnosis == "AD"&
                        comp_meta$TREM2Variant %in% c("CV", "R62H"),]
  meta_cl$TREM2Variant = factor(meta_cl$TREM2Variant, levels = c("CV", "R62H"))
  counts_cl = comp_counts[, meta_cl$cluster_sample]
  
  form_full = "~APOEgroup + CD33Group + BrainRegion + TREM2Variant"
  form_red = "~APOEgroup + CD33Group + BrainRegion"
  
  #remove spaces from formula to avoid problems with automatic removal of variables
  form_full = str_remove_all(form_full, " ")
  form_red = str_remove_all(form_red, " ")
  
  #extract variables in model
  model_vars_full = unlist(str_split(str_remove_all(form_full, "~"), "\\+"))
  model_vars_red = unlist(str_split(str_remove_all(form_red, "~"), "\\+"))
  
  
  ###check whether variables allow calculating model, remove colinear covariates
  
  #check whether model variables have multiple levels, if not, drop from model
  for (var1 in model_vars_red){
    
    meta_cl$model_var = meta_cl[[var1]]
    
    t2 = meta_cl %>% group_by(model_var) %>% summarise(N_samples = n())
    
    if (nrow(t2)==1){
      form_full = str_remove_all(form_full, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1))
      model_vars_red =  model_vars_red[model_vars_red != var1]
      
      msg = c(msg, paste0("            ! WARNING: Dropping '", var1, "' - All samples have same value \n"))
      message(msg)
    }
  }
  
  #check whether any reduced model variables are colinear, if so remove first variable
  v1 = model_vars_red
  
  for (var1 in v1){
    for (var2 in v1[v1 != var1]){

      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3 & str_detect(form_full, var2)){
        form_full = str_remove_all(form_full, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1))
        model_vars_red = model_vars_red[model_vars_red != var1]
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,"' => '", var1, "' dropped")
        message(v2)
        msg = c(msg, v2)
      }
      
      v1 = v1[v1 != var1]
      
    }
  }
  
  #check if covariates are colinear with main predictors of full vs reduced model => if so, omit cluster
  
  omit_cl = FALSE
  
  for (var1 in model_vars_full[!(model_vars_full %in% model_vars_red)]){
    for (var2 in model_vars_red){
      
      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3){
        omit_cl = TRUE
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,
                    "' => effect '", var1, "' cannot be determined => cluster ", cl, " omitted")
        message(v2)
        msg = c(msg, v2)
      }
    }
  }
  
  #if less samples than coefficients (variables+1) omit cluster (model can't be calculated)
  if (nrow(meta_cl) <= length(model_vars_full)+1){
    omit_cl = TRUE
    v1 = paste0("         WARNING: Not enough samples to calculate model => cluster ", cl," ommitted")
    message(v1)
    msg = c(msg, v1)
  }
  
  #if more samples than coefficients (variables+1) run DESeq2 (else model can't be calculated)
  if (omit_cl == FALSE){
    form_full = str_remove(form_full, "\\+$") #remove "+" in end if final variable has been dropped
    form_red = str_remove(form_red, "\\+$")
    dds = DESeqDataSetFromMatrix(counts_cl, colData = meta_cl, 
                                  design = as.formula(form_full))
    dds = DESeq(dds, test = "LRT", reduced = as.formula(form_red)) 
    
    bulk_data$deseq_dataset[[paste0(cl, "_AD_TREM2_R62H_vs_CV")]] = dds
  } 
  
  message(msg)
  
  bulk_data$deseq_info[[paste0(cl, "_AD_TREM2_R62H_vs_CV")]] = list(form_full = form_full,
                                                                         form_red = form_red,
                                                                         msg = msg)
  
}



#######################################
# Run Deseq analysis within clusters TREM2 R47H vs CV (only AD cases) 
#######################################
# for each cluster it tests TREM2 R47H vs CV in AD individuals, correcting for covariates (APOE, CD33, BrainRegion, Cohort).
cl = "AST_GFAP_s2" # changend from IRM_s14 for MIC

for (cl in comp_clusters){
  
  message("\n          *** Running DESeq2 analysis AD R47H vs CV by cluster - ", cl, " - ", Sys.time(),"\n")
  
  msg = NULL
  
  meta_cl = comp_meta[comp_meta$cluster_name == cl & 
                        comp_meta$NeuropathologicalDiagnosis == "AD"&
                        comp_meta$TREM2Variant %in% c("CV", "R47H"),]
  meta_cl$TREM2Variant = factor(meta_cl$TREM2Variant, levels = c("CV", "R47H"))
  counts_cl = comp_counts[, meta_cl$cluster_sample]
  
  form_full = "~APOEgroup + CD33Group + BrainRegion + TREM2Variant"
  form_red = "~APOEgroup + CD33Group + BrainRegion"
  
  #remove spaces from formula to avoid problems with automatic removal of variables
  form_full = str_remove_all(form_full, " ")
  form_red = str_remove_all(form_red, " ")
  
  #extract variables in model
  model_vars_full = unlist(str_split(str_remove_all(form_full, "~"), "\\+"))
  model_vars_red = unlist(str_split(str_remove_all(form_red, "~"), "\\+"))
  
  
  ###check whether variables allow calculating model, remove colinear covariates
  
  #check whether model variables have multiple levels, if not, drop from model
  for (var1 in model_vars_red){
    
    meta_cl$model_var = meta_cl[[var1]]
    
    t2 = meta_cl %>% group_by(model_var) %>% summarise(N_samples = n())
    
    if (nrow(t2)==1){
      form_full = str_remove_all(form_full, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1))
      model_vars_red =  model_vars_red[model_vars_red != var1]
      
      msg = c(msg, paste0("            ! WARNING: Dropping '", var1, "' - All samples have same value \n"))
      message(msg)
    }
  }
  
  #check whether any reduced model variables are colinear, if so remove first variable
  v1 = model_vars_red
  
  for (var1 in v1){
    for (var2 in v1[v1 != var1]){

      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3 & str_detect(form_full, var2)){
        form_full = str_remove_all(form_full, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1))
        model_vars_red = model_vars_red[model_vars_red != var1]
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,"' => '", var1, "' dropped")
        message(v2)
        msg = c(msg, v2)
      }
      
      v1 = v1[v1 != var1]
      
    }
  }
  
  #check if covariates are colinear with main predictors of full vs reduced model => if so, omit cluster
  
  omit_cl = FALSE
  
  for (var1 in model_vars_full[!(model_vars_full %in% model_vars_red)]){
    for (var2 in model_vars_red){
      
      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3){
        omit_cl = TRUE
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,
                    "' => effect '", var1, "' cannot be determined => cluster ", cl, " omitted")
        message(v2)
        msg = c(msg, v2)
      }
    }
  }
  
  #if less samples than coefficients (variables+1) omit cluster (model can't be calculated)
  if (nrow(meta_cl) <= length(model_vars_full)+1){
    omit_cl = TRUE
    v1 = paste0("         WARNING: Not enough samples to calculate model => cluster ", cl," ommitted")
    message(v1)
    msg = c(msg, v1)
  }
  
  #if more samples than coefficients (variables+1) run DESeq2 (else model can't be calculated)
  if (omit_cl == FALSE){
    form_full = str_remove(form_full, "\\+$") #remove "+" in end if final variable has been dropped
    form_red = str_remove(form_red, "\\+$")
    dds = DESeqDataSetFromMatrix(counts_cl, colData = meta_cl, 
                                  design = as.formula(form_full))
    dds = DESeq(dds, test = "LRT", reduced = as.formula(form_red)) 
    
    bulk_data$deseq_dataset[[paste0(cl, "_AD_TREM2_R47H_vs_CV")]] = dds
  } 
  
  message(msg)
  
  bulk_data$deseq_info[[paste0(cl, "_AD_TREM2_R47H_vs_CV")]] = list(form_full = form_full,
                                                                         form_red = form_red,
                                                                         msg = msg)
  
}




#######################################
# Run Deseq analysis within clusters TREM2 R47H vs R62H (only AD cases) 
#######################################
# for each cluster it tests TREM2 R47H vs R62H in AD individuals, correcting for covariates (APOE, CD33, BrainRegion, Cohort).
cl = "AST_GFAP_s2" # changed from IRM_s14 for MIC

for (cl in comp_clusters){
  
  message("\n          *** Running DESeq2 analysis AD R47H vs R62H by cluster - ", cl, " - ", Sys.time(),"\n")
  
  msg = NULL
  
  meta_cl = comp_meta[comp_meta$cluster_name == cl & 
                        comp_meta$NeuropathologicalDiagnosis == "AD"&
                        comp_meta$TREM2Variant %in% c("R62H", "R47H"),]
  meta_cl$TREM2Variant = factor(meta_cl$TREM2Variant, levels = c("R62H", "R47H"))
  counts_cl = comp_counts[, meta_cl$cluster_sample]
  
  form_full = "~APOEgroup + CD33Group + BrainRegion + TREM2Variant"
  form_red = "~APOEgroup + CD33Group + BrainRegion"
  
  #remove spaces from formula to avoid problems with automatic removal of variables
  form_full = str_remove_all(form_full, " ")
  form_red = str_remove_all(form_red, " ")
  
  #extract variables in model
  model_vars_full = unlist(str_split(str_remove_all(form_full, "~"), "\\+"))
  model_vars_red = unlist(str_split(str_remove_all(form_red, "~"), "\\+"))
  
  
  ###check whether variables allow calculating model, remove colinear covariates
  
  #check whether model variables have multiple levels, if not, drop from model
  for (var1 in model_vars_red){
    
    meta_cl$model_var = meta_cl[[var1]]
    
    t2 = meta_cl %>% group_by(model_var) %>% summarise(N_samples = n())
    
    if (nrow(t2)==1){
      form_full = str_remove_all(form_full, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1, "\\+"))
      form_red = str_remove_all(form_red, paste0(var1))
      model_vars_red =  model_vars_red[model_vars_red != var1]
      
      msg = c(msg, paste0("            ! WARNING: Dropping '", var1, "' - All samples have same value \n"))
      message(msg)
    }
  }
  
  #check whether any reduced model variables are colinear, if so remove first variable
  v1 = model_vars_red
  
  for (var1 in v1){
    for (var2 in v1[v1 != var1]){
      
      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3 & str_detect(form_full, var2)){
        form_full = str_remove_all(form_full, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1, "\\+"))
        form_red = str_remove_all(form_red, paste0(var1))
        model_vars_red = model_vars_red[model_vars_red != var1]
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,"' => '", var1, "' dropped")
        message(v2)
        msg = c(msg, v2)
      }
      
      v1 = v1[v1 != var1]
      
    }
  }
  
  #check if covariates are colinear with main predictors of full vs reduced model => if so, omit cluster
  
  omit_cl = FALSE
  
  for (var1 in model_vars_full[!(model_vars_full %in% model_vars_red)]){
    for (var2 in model_vars_red){
      
      t2 = meta_cl %>% group_by(pick(all_of(c(var1, var2)))) %>% summarise(N_samples = n())
      
      if (nrow(t2)<3){
        omit_cl = TRUE
        v2 = paste0("         WARNING: Colinearity '", var1, "' and '", var2,
                    "' => effect '", var1, "' cannot be determined => cluster ", cl, " omitted")
        message(v2)
        msg = c(msg, v2)
      }
    }
  }
  
  #if less samples than coefficients (variables+1) omit cluster (model can't be calculated)
  if (nrow(meta_cl) <= length(model_vars_full)+1){
    omit_cl = TRUE
    v1 = paste0("         WARNING: Not enough samples to calculate model => cluster ", cl," ommitted")
    message(v1)
    msg = c(msg, v1)
  }
  
  #if more samples than coefficients (variables+1) run DESeq2 (else model can't be calculated)
  if (omit_cl == FALSE){
    form_full = str_remove(form_full, "\\+$") #remove "+" in end if final variable has been dropped
    form_red = str_remove(form_red, "\\+$")
    dds = DESeqDataSetFromMatrix(counts_cl, colData = meta_cl, 
                                 design = as.formula(form_full))
    dds = DESeq(dds, test = "LRT", reduced = as.formula(form_red)) 
    
    bulk_data$deseq_dataset[[paste0(cl, "_AD_TREM2_R47H_vs_R62H")]] = dds
  } 
  
  message(msg)
  
  bulk_data$deseq_info[[paste0(cl, "_AD_TREM2_R47H_vs_R62H")]] = list(form_full = form_full,
                                                                    form_red = form_red,
                                                                    msg = msg)
  
}




#####################################
# extract DESeq results and DEGs
#####################################

bulk_data$deseq_results = list()

for (comp1 in names(bulk_data$deseq_dataset)){
  
  dds = bulk_data$deseq_dataset[[comp1]]
  
  t0 = as.data.frame(results(dds))
  t1 = cbind(gene = rownames(t0), t0)
  bulk_data$deseq_results[[comp1]] = t1
  
  t2 = t1[!is.na(t1$padj) & t1$padj<0.1,]
  bulk_data$DEGs[[paste0(comp1, "_up")]] = t2$gene[t2$log2FoldChange>0]
  bulk_data$DEGs[[paste0(comp1, "_down")]] = t2$gene[t2$log2FoldChange<0]
  
}


#save bulk_dataset with DESeq results

qsave(bulk_data, file = paste0(out_dir,script_ind, "bulk_data.qs")) 




#################################################
# summarise all DEGs (all clusters combined and by cluster)
#################################################

v1 = unique(unlist(bulk_data$DEGs))

t1 = tibble(N_DEGs_all = length(v1),
            N_DEGs_all_TF = length(intersect(v1, GOI$TF)),)

write_csv(t1, file = paste0(out_dir,script_ind, "DEGs_all_clusters_combined_N_genes.csv"))



### save table with DEGs by cluster and TFs

l1 = bulk_data$DEGs
l2 = lapply(l1, function(x){x = x[x%in% GOI$TF]})
names(l2) = paste0(names(l1), "_TF")

l3 = c(l1, l2)

m1 = matrix(nrow = max(lengths(l3)), ncol = length(l3))
colnames(m1) = names(l3)

for (i in names(l3)){
  v1 = l3[[i]]
  if(length(v1)>0){
    m1[1:length(v1),i] = v1
  }
}
m1[is.na(m1)] = ""

write_csv(as_tibble(m1), file = paste0(out_dir,script_ind, "DEGs_by_cluster_genes.csv"))

t1 = tibble(gene_set = names(l3), N_genes = lengths(l3))

write_csv(t1, file = paste0(out_dir,script_ind, "DEGs_by_cluster_N.csv"))



#################################################
# plot heatmap top3000 variable genes by cluster_sample
#################################################

vst_mat = bulk_data$vst_mat

#identify top 3000 variable genes
v1 = rowVars(vst_mat)
pl_genes = names(v1[order(-v1)][1:3000])

pl_mat_X = bulk_data$gene_Z_scores$clusters_combined[pl_genes,]
lims_X = 0.3*c(-max(abs(pl_mat_X)), max(abs(pl_mat_X)))

names(meta)

pdf(file = paste0(out_dir,script_ind, "Gene_expr_heatmap_var_genes_top3000.pdf"), 
    width = 15, height = 30)
{
  p1 = bulkdata_heatmap(pl_mat = pl_mat_X, 
                        pl_meta = meta,
                        pl_genes = pl_genes,
                        x_col = "cluster_sample", 
                        meta_annot_cols = c("TREM2Variant","NeuropathologicalDiagnosis",
                                            "CD33Group","APOEgroup", "cohort",
                                            "cluster_name"),
                        show_rownames = FALSE, show_colnames = FALSE,
                        cluster_rows = TRUE, cluster_cols = FALSE,
                        color = viridis(250),
                        lims = lims_X,  cellwidth = 2, cellheight = 0.2, 
                        fontsize = 5, title = paste0("Top3000 variable genes - Z-score"))
  
}
dev.off()



#################################################
# plot heatmap DEGs combined by cluster_sample
#################################################

vst_mat = bulk_data$vst_mat

pl_genes = unique(unlist(bulk_data$DEGs))

pl_mat_X = bulk_data$gene_Z_scores$clusters_combined[pl_genes,]
lims_X = 0.3*c(-max(abs(pl_mat_X)), max(abs(pl_mat_X)))

names(meta)

pdf(file = paste0(out_dir,script_ind, "Gene_expr_heatmap_DEGs_comb.pdf"), 
    width = 15, height = 30)
{
  p1 = bulkdata_heatmap(pl_mat = pl_mat_X, 
                        pl_meta = meta,
                        pl_genes = pl_genes,
                        x_col = "cluster_sample", 
                        meta_annot_cols = c("TREM2Variant","NeuropathologicalDiagnosis",
                                            "CD33Group","APOEgroup", "cohort",
                                            "cluster_name"),
                        show_rownames = FALSE, show_colnames = FALSE,
                        cluster_rows = TRUE, cluster_cols = FALSE,
                        color = viridis(250),
                        lims = lims_X,  cellwidth = 2, cellheight = 2, 
                        fontsize = 5, title = paste0("Combined DEGs - Z-score"))
  
}
dev.off()



###########################################################
# plot volcano plots with DEGs highlighted
###########################################################

pl = list()

for (comp in names(bulk_data$deseq_results)){
  
  t1 = bulk_data$deseq_results[[comp]]
  t1 = t1[!is.na(t1$padj),]
  t1$log10pval = log10(t1$pvalue)
  t1$log10padj = log10(t1$padj)
  t1$DEG = t1$padj <= 0.1
  t1$highlight = t1$DEG
  
  t1$gene_cat = "Other"
  t1$gene_cat[t1$DEG & t1$log2FoldChange>0] = "up"
  t1$gene_cat[t1$DEG & t1$log2FoldChange<0] = "down"
  
  t1$plot_label = ""
  
  t3 = t1[order(t1$log10pval),]
  t4 = t1[order(t1$log2FoldChange),]
  t5 = t1[order(-t1$log2FoldChange),]
  v5 = unique(c(rownames(t3)[1:20], rownames(t4)[1:20], rownames(t5)[1:20]))
  
  t1$plot_label[rownames(t1) %in% v5] = rownames(t1)[rownames(t1) %in% v5]
  
  pl[[comp]] = ggplot(t1, aes(x = log2FoldChange, y = -log10pval, color = gene_cat))+
    geom_vline(xintercept = c(-log2(1.2), log2(1.2)), linewidth = 0.3, color = "grey30", linetype = 2)+
    geom_hline(yintercept = -log10(0.1), linewidth = 0.3, color = "grey30", linetype = 2)+
    geom_point(aes(size = highlight), alpha = 0.8)+
    geom_label_repel(aes(label = plot_label), seed = 42, min.segment.length = 0, max.overlaps = Inf,
                     max.time = 5)+
    scale_size_manual(limits = c(FALSE, TRUE), values = c(1, 2))+
    scale_color_manual(limits = c("up", "Other", "down"), 
                       values = c("red", "grey40", "blue"))+
    theme_minimal()+
    labs(title = comp)
  
}


pdf(file = paste0(out_dir,script_ind, "Volcano_plots_DEGs_by_comp_group_cluster.pdf"), 
    width = 10, height = 8)
{
  lapply(pl, function(x){x})
}
dev.off()





#get info on version of R, used packages etc
sessionInfo()

message("\n\n##########################################################################\n",
        "# Completed LD_E02a2 ", Sys.time(),
        "\n##########################################################################\n",
        "\n##########################################################################\n\n\n")


